Repository futureleadersupc/waw-frontend-vue, pull requests merged in 2022-06, with the labels that each got.

#38 refactor(service): Service Injection
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/accounts/services/auth.service.js
  src/core/components/base-header.vue
  src/core/services/base.service.js
  src/core/utils/keys.js
  src/home/pages/home-profile.component.vue
  src/jobs/pages/job-offers-display.component.vue
  src/jobs/services/jobs.service.js
  src/main.js
Labels: refactor, scope: service

#36 feat(ui): list of applicants v1
  src/jobs/pages/job-offers-admin.component.vue
Labels: enhancement

#40 refactor(service): Service Injection
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/accounts/services/auth.service.js
  src/core/components/base-header.vue
  src/core/services/base.service.js
  src/core/utils/keys.js
  src/home/pages/home-profile.component.vue
  src/jobs/pages/job-offers-display.component.vue
  src/jobs/services/jobs.service.js
  src/main.js
Labels: refactor, scope: service

#42 ci: add base branch check for PRs
  .github/workflows/branches.yml
Labels: ci

#44 ci: branch check fixes
  .github/workflows/branches.yml
Labels: ci

#43 release: v0.3.0
  src/jobs/pages/job-offers-admin.component.vue
Labels: enhancement

#45 ci: workflow improvements and various fixes
  .commitlintrc.json
  .eslintignore
  .github/workflows/branches.yml
  .github/workflows/node.yml
  .github/workflows/reviewdog.yml
  .github/workflows/tests.yml
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .stylelintignore
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  commitlint.config.js
  package-lock.json
  package.json
Labels: ci

#46 feat(offer): refinement and implementation of new features
  src/jobs/pages/job-offers-admin.component.vue
Labels: enhancement

#47 feat: Companies component
  server/db.json
  src/employers/pages/companies-admin.component.vue
  src/employers/services/companies.service.js
  src/router/routes.js
Labels: enhancement

#48 refactor(service): Service Injection
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/accounts/services/auth.service.js
  src/core/components/base-header.vue
  src/core/services/base.service.js
  src/core/utils/keys.js
  src/home/pages/home-profile.component.vue
  src/jobs/pages/job-offers-display.component.vue
  src/jobs/services/jobs.service.js
  src/main.js
Labels: enhancement

#49 refactor: Job Offers Admin
  src/assets/base.css
  src/jobs/pages/job-offers-admin.component.vue
Labels: refactor

#52 feat(companies): added linker to the companies interface in the profile menu
  src/core/components/base-header.vue
Labels: enhancement
