Repository futureleadersupc/waw-frontend-vue, pull requests merged in 2022-05, with the labels that each got.

#3 chore(linters): update eslint rules
  .eslintrc.js
Labels: chore, scope: linters

#2 refactor(router): rewrite of router
  src/main.js
  src/router/index.js
  src/router/routes.js
Labels: refactor, scope: router

#1 chore(deps): add PrimeVue framework
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/views/TestView.vue
Labels: chore, scope: deps

#5 chore: remove defaults
  index.html
  src/App.vue
  src/__tests__/App.spec.js
  src/assets/base.css
  src/assets/logo.svg
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/__tests__/.gitkeep
  src/components/__tests__/HelloWorld.spec.js
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/router/routes.js
  src/views/AboutView.vue
  src/views/HomeView.vue
  src/views/TestView.vue
Labels: chore

#6 chore: add Tailwind CSS support
  .vscode/extensions.json
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.vue
  src/assets/base.css
  src/main.js
  stylelint.config.js
  tailwind.config.js
Labels: chore, scope: linters, scope: deps

#4 chore(json-server): initial implementation of `json-server`
  package-lock.json
  package.json
  server/db.json
  server/routes.json
Labels: chore, scope: json-server

#8 chore(ext): prevent recommendation of Vetur
  .vscode/extensions.json
Labels: chore, scope: ext

#9 chore(auth): added initial setup files
  src/security/pages/reset-password.component.vue
  src/security/pages/sign-in.component.vue
  src/security/pages/sign-up.component.vue
  src/security/services/authentication.service.js
Labels: chore, scope: auth

#7 feat(ui): implemented base layout
  package-lock.json
  package.json
  src/App.vue
  src/__tests__/App.spec.js
  src/assets/base.css
  src/components/base-footer.vue
  src/components/base-header.vue
  src/main.js
  tailwind.config.js
Labels: enhancement, scope: ui

#11 feat(ui): sign-up component
  src/security/pages/sign-up.component.vue
Labels: enhancement, scope: auth

#10 chore(ide): disable ESLint and Stylelint on save
  .idea/jsLinters/eslint.xml
  .vscode/settings.json
Labels: chore, scope: ide

#12 feat(auth): implemented sign-in component
  src/security/pages/sign-in.component.vue
Labels: enhancement, scope: ui, scope: auth

#13 feat(service): http common
  .env.example
  package-lock.json
  package.json
  src/core/services/http-common.js
Labels: enhancement, scope: service

#14 ci(json-server): add workflow to push to fake api repo
  .github/workflows/json-server.yml
  server/db.json
Labels: ci, scope: json-server

#15 fix(ci): publish workflow
  .github/workflows/json-server.yml
Labels: bug, ci

#16 feat: home-page
  src/home/pages/home-profile.vue
Labels: enhancement

#17 fix: update Volar extension id
  .vscode/extensions.json
Labels: bug, scope: ext

#19 feat(ui): link everything
  .eslintrc.js
  src/App.vue
  src/__tests__/App.spec.js
  src/accounts/pages/reset-password.component.vue
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/accounts/services/authentication.service.js
  src/core/components/base-footer.vue
  src/core/components/base-header.vue
  src/home/pages/home-profile.component.vue
  src/jobs/pages/job-offers-admin.component.vue
  src/jobs/services/job-offers.service.js
  src/router/routes.js
  src/security/pages/reset-password.component.vue
  src/security/services/authentication.service.js
Labels: enhancement, scope: ui

#20 chore: update org name
  .github/workflows/json-server.yml
Labels: chore

#22 chore(sync): initial setup of fake API file sync
  .github/sync.yml
  .github/workflows/json-server.yml
  .github/workflows/sync.yml
Labels: chore, scope: sync

#24 feat(fix): Update jobs.services.js name file
  src/jobs/pages/job-offers-admin.component.vue
  src/jobs/services/job-offers.service.js
  src/jobs/services/jobs.service.js
Labels: bug

#26 fix(avatar): fixed avatar size
  src/home/pages/home-profile.component.vue
Labels: bug, scope: ui

#28 build: Reactivity Transform
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/core/components/base-footer.vue
  src/core/components/base-header.vue
  src/home/pages/home-profile.component.vue
  vite.config.js
Labels: build

#29 feat(ui): job offers searching page for employees
  src/jobs/pages/job-offers-display.component.vue
Labels: enhancement, scope: ui

#25 feat(ui): jobs manager version 2
  server/db.json
  src/jobs/pages/job-offers-admin.component.vue
Labels: enhancement, scope: ui

#33 refactor: services
  src/accounts/pages/sign-in.component.vue
  src/accounts/pages/sign-up.component.vue
  src/accounts/services/auth.service.js
  src/accounts/services/authentication.service.js
  src/core/components/base-header.vue
  src/core/services/base.service.js
  src/home/pages/home-profile.component.vue
  src/jobs/services/jobs.service.js
Labels: refactor

#32 fix: update home page
  src/core/utils/months.js
  src/home/pages/home-profile.component.vue
Labels: bug

#31 feat(jobs): added confirmation and toast services
  src/core/components/base-header.vue
  src/jobs/pages/job-offers-display.component.vue
  src/main.js
  src/router/routes.js
Labels: enhancement, scope: ui

#34 fix: replace inline styles with tailwind classes
  src/jobs/pages/job-offers-admin.component.vue
Labels: bug
